apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-platform-app
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/ganeshprajapath733/production-grade-devops-platform.git
    targetRevision: HEAD
    path: kubernetes

  destination:
    server: https://kubernetes.default.svc
    namespace: devops-platform

  syncPolicy:
    automated:
      prune: true
      selfHeal: true